version: '3.9'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data 
  prometheus:
    image: prom/prometheus
    volumes:
      - './etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - "prometheus-data:/prometheus"
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment: 
      DATA_SOURCE_NAME: "postgresql://postgres:example@db:5432/postgres?sslmode=disable"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
volumes:
  db-data:
  prometheus-data:
  grafana-data: